# Flash Attention implementation using Triton.
# Generated by DeepSeek-V4-Pro.

import torch
import triton
import triton.language as tl
import math


@triton.jit
def _fwd_kernel(
    Q, K, V, Mask, O, LSE,
    softmax_scale,
    stride_qb, stride_qn, stride_qd,
    stride_kb, stride_kn, stride_kd,
    stride_vb, stride_vn, stride_vd,
    stride_mb, stride_mn, stride_mm,
    stride_ob, stride_on, stride_od,
    stride_lse_b, stride_lse_n,
    N, D,
    BLOCK_M: tl.constexpr,
    BLOCK_N: tl.constexpr,
    BLOCK_D: tl.constexpr,
    HAS_MASK: tl.constexpr,
):
    '''
    Forward kernel for FlashAttention with optional additive mask.

    Computes O = softmax(QK^T * scale + mask) V in a block-wise manner using online softmax.
    Saves the log-sum-exp (LSE) for each query row to allow exact recomputation in the backward pass.
    '''

    pid_bh = tl.program_id(1)
    pid_m = tl.program_id(0)

    start_m = pid_m * BLOCK_M
    offs_m = start_m + tl.arange(0, BLOCK_M)
    offs_d = tl.arange(0, BLOCK_D)

    mask_m = offs_m < N
    mask_d = offs_d < D

    q = tl.load(Q + pid_bh * stride_qb + offs_m[:, None] * stride_qn + offs_d[None, :] * stride_qd,
                mask=mask_m[:, None] & mask_d[None, :], other=0.0)

    m_i = tl.full([BLOCK_M], float('-inf'), dtype=tl.float32)
    l_i = tl.zeros([BLOCK_M], dtype=tl.float32)
    acc_o = tl.zeros([BLOCK_M, BLOCK_D], dtype=tl.float32)

    for start_n in range(0, N, BLOCK_N):
        offs_n = start_n + tl.arange(0, BLOCK_N)
        mask_n = offs_n < N

        k = tl.load(K + pid_bh * stride_kb + offs_n[:, None] * stride_kn + offs_d[None, :] * stride_kd,
                    mask=mask_n[:, None] & mask_d[None, :], other=0.0)

        s = tl.dot(q, tl.trans(k), out_dtype=tl.float32) * softmax_scale

        if HAS_MASK:
            mask_block = tl.load(Mask + pid_bh * stride_mb + offs_m[:, None] * stride_mn + offs_n[None, :] * stride_mm,
                                 mask=mask_m[:, None] & mask_n[None, :], other=0.0)
            s += mask_block

        s = tl.where(mask_n[None, :], s, float('-inf'))

        m_old = m_i
        m_new = tl.maximum(m_old, tl.max(s, axis=1))
        p = tl.exp(s - m_new[:, None])
        l_new = tl.exp(m_old - m_new) * l_i + tl.sum(p, axis=1)

        v = tl.load(V + pid_bh * stride_vb + offs_n[:, None] * stride_vn + offs_d[None, :] * stride_vd,
                    mask=mask_n[:, None] & mask_d[None, :], other=0.0)

        acc_o = tl.exp(m_old - m_new)[:, None] * acc_o + tl.dot(p, v)
        m_i = m_new
        l_i = l_new

    acc_o = acc_o / l_i[:, None]
    lse = m_i + tl.log(l_i)

    tl.store(O + pid_bh * stride_ob + offs_m[:, None] * stride_on + offs_d[None, :] * stride_od,
             acc_o.to(O.dtype.element_ty), mask=mask_m[:, None] & mask_d[None, :])

    tl.store(LSE + pid_bh * stride_lse_b + offs_m * stride_lse_n,
             lse, mask=mask_m)



@triton.jit
def _bwd_kernel(
    Q, K, V, Mask, O, dO, dQ, dK, dV, LSE,
    softmax_scale,
    stride_qb, stride_qn, stride_qd,
    stride_kb, stride_kn, stride_kd,
    stride_vb, stride_vn, stride_vd,
    stride_mb, stride_mn, stride_mm,
    stride_ob, stride_on, stride_od,
    stride_dob, stride_don, stride_dod,
    stride_dqb, stride_dqn, stride_dqd,
    stride_dkb, stride_dkn, stride_dkd,
    stride_dvb, stride_dvn, stride_dvd,
    stride_lse_b, stride_lse_n,
    N, D,
    BLOCK_M: tl.constexpr,
    BLOCK_N: tl.constexpr,
    BLOCK_D: tl.constexpr,
    HAS_MASK: tl.constexpr,
):
    '''
    Backward kernel for FlashAttention with optional additive mask.

    Recomputes attention probabilities using the saved LSE and the same mask as forward.
    Computes gradients dQ, dK, dV. dK and dV are accumulated atomically because multiple
    query blocks contribute to the same key/value block.
    '''

    pid_bh = tl.program_id(1)
    pid_m = tl.program_id(0)

    start_m = pid_m * BLOCK_M
    offs_m = start_m + tl.arange(0, BLOCK_M)
    offs_d = tl.arange(0, BLOCK_D)

    mask_m = offs_m < N
    mask_d = offs_d < D

    q = tl.load(Q + pid_bh * stride_qb + offs_m[:, None] * stride_qn + offs_d[None, :] * stride_qd,
                mask=mask_m[:, None] & mask_d[None, :], other=0.0)
    do = tl.load(dO + pid_bh * stride_dob + offs_m[:, None] * stride_don + offs_d[None, :] * stride_dod,
                 mask=mask_m[:, None] & mask_d[None, :], other=0.0)
    o = tl.load(O + pid_bh * stride_ob + offs_m[:, None] * stride_on + offs_d[None, :] * stride_od,
                mask=mask_m[:, None] & mask_d[None, :], other=0.0)
    lse_i = tl.load(LSE + pid_bh * stride_lse_b + offs_m * stride_lse_n, mask=mask_m, other=0.0)

    D_i = tl.sum(do * o, axis=1)

    dq_acc = tl.zeros([BLOCK_M, BLOCK_D], dtype=tl.float32)

    for start_n in range(0, N, BLOCK_N):
        offs_n = start_n + tl.arange(0, BLOCK_N)
        mask_n = offs_n < N

        k = tl.load(K + pid_bh * stride_kb + offs_n[:, None] * stride_kn + offs_d[None, :] * stride_kd,
                    mask=mask_n[:, None] & mask_d[None, :], other=0.0)
        v = tl.load(V + pid_bh * stride_vb + offs_n[:, None] * stride_vn + offs_d[None, :] * stride_vd,
                    mask=mask_n[:, None] & mask_d[None, :], other=0.0)

        s = tl.dot(q, tl.trans(k), out_dtype=tl.float32) * softmax_scale

        if HAS_MASK:
            mask_block = tl.load(Mask + pid_bh * stride_mb + offs_m[:, None] * stride_mn + offs_n[None, :] * stride_mm,
                                 mask=mask_m[:, None] & mask_n[None, :], other=0.0)
            s += mask_block

        s = tl.where(mask_n[None, :], s, float('-inf'))

        p = tl.exp(s - lse_i[:, None])

        dv = tl.dot(tl.trans(p), do, out_dtype=tl.float32)
        dv_ptrs = dV + pid_bh * stride_dvb + offs_n[:, None] * stride_dvn + offs_d[None, :] * stride_dvd
        tl.atomic_add(dv_ptrs, dv.to(dV.dtype.element_ty), mask=mask_n[:, None] & mask_d[None, :])

        dp = tl.dot(do, tl.trans(v), out_dtype=tl.float32)
        ds = p * (dp - D_i[:, None]) * softmax_scale

        dq_acc += tl.dot(ds, k, out_dtype=tl.float32)

        dk = tl.dot(tl.trans(ds), q, out_dtype=tl.float32)
        dk_ptrs = dK + pid_bh * stride_dkb + offs_n[:, None] * stride_dkn + offs_d[None, :] * stride_dkd
        tl.atomic_add(dk_ptrs, dk.to(dK.dtype.element_ty), mask=mask_n[:, None] & mask_d[None, :])

    dq_ptrs = dQ + pid_bh * stride_dqb + offs_m[:, None] * stride_dqn + offs_d[None, :] * stride_dqd
    tl.store(dq_ptrs, dq_acc.to(dQ.dtype.element_ty), mask=mask_m[:, None] & mask_d[None, :])


class FlashAttention(torch.autograd.Function):
    @staticmethod
    def forward(ctx, q, k, v, attention_mask, scaling):
        batch, heads, N, D = q.shape
        assert k.shape == q.shape and v.shape == q.shape

        if scaling is None:
            scaling = 1.0 / math.sqrt(D)

        q = q.contiguous().view(batch * heads, N, D)
        k = k.contiguous().view(batch * heads, N, D)
        v = v.contiguous().view(batch * heads, N, D)

        has_mask = attention_mask is not None
        if has_mask:
            attention_mask = attention_mask.expand(batch, heads, N, N).contiguous().view(batch * heads, N, N)

        o = torch.empty_like(q)
        lse = torch.empty((batch * heads, N), device=q.device, dtype=torch.float32)

        BLOCK_D = max(16, triton.next_power_of_2(D))
        BLOCK_M = max(16, min(64, triton.next_power_of_2(N)))
        BLOCK_N = max(16, min(64, triton.next_power_of_2(N)))

        grid = (triton.cdiv(N, BLOCK_M), batch * heads)

        mask_arg = attention_mask if has_mask else q  # dummy tensor, not used when HAS_MASK=False
        _fwd_kernel[grid](
            q, k, v, mask_arg, o, lse,
            scaling,
            q.stride(0), q.stride(1), q.stride(2),
            k.stride(0), k.stride(1), k.stride(2),
            v.stride(0), v.stride(1), v.stride(2),
            mask_arg.stride(0), mask_arg.stride(1), mask_arg.stride(2) if has_mask else (0, 0, 0),
            o.stride(0), o.stride(1), o.stride(2),
            lse.stride(0), lse.stride(1),
            N, D,
            BLOCK_M=BLOCK_M, BLOCK_N=BLOCK_N, BLOCK_D=BLOCK_D,
            HAS_MASK=has_mask,
        )

        ctx.save_for_backward(q, k, v, o, lse, attention_mask if has_mask else torch.empty(0, device=q.device))
        ctx.has_mask = has_mask
        ctx.scaling = scaling
        ctx.BLOCK_M = BLOCK_M
        ctx.BLOCK_N = BLOCK_N
        ctx.BLOCK_D = BLOCK_D
        ctx.batch = batch
        ctx.heads = heads
        ctx.N = N
        ctx.D = D

        return o.view(batch, heads, N, D)

    @staticmethod
    def backward(ctx, do):
        q, k, v, o, lse, saved_mask = ctx.saved_tensors
        scaling = ctx.scaling
        has_mask = ctx.has_mask
        BLOCK_M = ctx.BLOCK_M
        BLOCK_N = ctx.BLOCK_N
        BLOCK_D = ctx.BLOCK_D
        batch = ctx.batch
        heads = ctx.heads
        N = ctx.N
        D = ctx.D

        do = do.contiguous().view(batch * heads, N, D)
        bh = q.shape[0]

        dq = torch.zeros_like(q, dtype=torch.float32)
        dk = torch.zeros_like(k, dtype=torch.float32)
        dv = torch.zeros_like(v, dtype=torch.float32)

        grid = (triton.cdiv(N, BLOCK_M), bh)

        mask_arg = saved_mask if has_mask else q  # dummy
        _bwd_kernel[grid](
            q, k, v, mask_arg, o, do, dq, dk, dv, lse,
            scaling,
            q.stride(0), q.stride(1), q.stride(2),
            k.stride(0), k.stride(1), k.stride(2),
            v.stride(0), v.stride(1), v.stride(2),
            mask_arg.stride(0), mask_arg.stride(1), mask_arg.stride(2) if has_mask else (0, 0, 0),
            o.stride(0), o.stride(1), o.stride(2),
            do.stride(0), do.stride(1), do.stride(2),
            dq.stride(0), dq.stride(1), dq.stride(2),
            dk.stride(0), dk.stride(1), dk.stride(2),
            dv.stride(0), dv.stride(1), dv.stride(2),
            lse.stride(0), lse.stride(1),
            N, D,
            BLOCK_M=BLOCK_M, BLOCK_N=BLOCK_N, BLOCK_D=BLOCK_D,
            HAS_MASK=has_mask,
        )

        dq = dq.view(batch, heads, N, D).to(do.dtype)
        dk = dk.view(batch, heads, N, D).to(do.dtype)
        dv = dv.view(batch, heads, N, D).to(do.dtype)

        return dq, dk, dv, None, None


def attn(query, key, value, attention_mask=None, scaling=None):
    '''
    FlashAttention with optional additive mask.

    Args:
        query, key, value: tensors of shape [batch, heads, seq_len, head_dim]
        attention_mask: additive mask broadcastable to [batch, heads, seq_len, seq_len]
                        (e.g. causal mask with -inf for masked positions)
        scaling: optional softmax scaling factor, defaults to 1/sqrt(head_dim)

    Returns:
        output tensor of the same shape as query
    '''
    return FlashAttention.apply(query, key, value, attention_mask, scaling)


def test():
    '''
    Validates the custom FlashAttention against PyTorch's scaled_dot_product_attention.

    Tests both with and without an explicit additive mask.
    '''
    torch.manual_seed(0)
    batch, heads, seq_len, dim = 2, 4, 128, 64
    device = 'cuda' if torch.cuda.is_available() else 'cpu'
    dtype = torch.float32

    q = torch.randn(batch, heads, seq_len, dim, device=device, dtype=dtype, requires_grad=True)
    k = torch.randn(batch, heads, seq_len, dim, device=device, dtype=dtype, requires_grad=True)
    v = torch.randn(batch, heads, seq_len, dim, device=device, dtype=dtype, requires_grad=True)

    mask_cases = [None]
    # Create a simple block mask: mask out the last 10 keys for all queries
    block_mask = torch.zeros(seq_len, seq_len, device=device, dtype=dtype)
    block_mask[:, -10:] = float('-inf')
    mask_cases.append(block_mask[None, None, :, :].expand(batch, heads, seq_len, seq_len))

    for mask in mask_cases:
        out_custom = attn(q, k, v, attention_mask=mask)
        out_ref = torch.nn.functional.scaled_dot_product_attention(
            q, k, v, attn_mask=mask if mask is not None else None
        )

        fwd_err = (out_custom - out_ref).abs().max().item()
        print(f'Mask={mask is not None}, forward max abs error: {fwd_err:.6e}')

        grad_out = torch.randn_like(out_ref)
        q.grad = k.grad = v.grad = None  # clear previous grads
        out_custom.backward(grad_out, retain_graph=True)
        q_grad_custom = q.grad.clone()
        k_grad_custom = k.grad.clone()
        v_grad_custom = v.grad.clone()

        q.grad = k.grad = v.grad = None
        out_ref.backward(grad_out, retain_graph=True)
        q_grad_ref = q.grad.clone()
        k_grad_ref = k.grad.clone()
        v_grad_ref = v.grad.clone()

        grad_q_err = (q_grad_custom - q_grad_ref).abs().max().item()
        grad_k_err = (k_grad_custom - k_grad_ref).abs().max().item()
        grad_v_err = (v_grad_custom - v_grad_ref).abs().max().item()

        print(f'Mask={mask is not None}, dQ error: {grad_q_err:.6e}, dK error: {grad_k_err:.6e}, dV error: {grad_v_err:.6e}')

        assert fwd_err < 1e-4, f'Forward error too large: {fwd_err}'
        assert grad_q_err < 1e-4 and grad_k_err < 1e-4 and grad_v_err < 1e-4

    print('All tests passed.')

if __name__ == '__main__':
    test()

__all__ = ['attn']